config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get "my_cocktails", to: "users#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  resources :cocktails, except: [:edit, :update] do
    resources :doses, only: [:new, :create, :destroy], shallow: true
  end
  mount Attachinary::Engine => "/attachinary"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cocktails, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_name,
    against: [:name],
    using: { tsearch: { prefix: true }}

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, :dependent => :restrict_with_exception
  validates :name, uniqueness: true, presence: true
  has_attachment :photo
  belongs_to :user
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :cocktails, dependent: :destroy
  acts_as_token_authenticatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from StandardError,                with: :internal_server_error
  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, error: exception.message }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/cocktails_controller.rb
class Api::V1::CocktailsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, except: [:index, :show]
  before_action :set_cocktail, only: [:show, :update, :destroy]
  def index
    @cocktails = policy_scope(Cocktail)
  end

  def show
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    authorize @cocktail
    if @cocktail.save
      render :show, status: :created
    else
      render_error
    end
  end

  def update
    if @cocktail.update(cocktail_params)
      render :show
    else
      render_error
    end
  end

  def destroy
    @cocktail.destroy
    head :no_content
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
  end

  def render_error
    render json: { errors: @cocktail.errors.full_messages },
      status: :unprocessable_entity
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

  # Pundit: white-list
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def resource_not_found # see in record's controller
  end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    if params[:query].present?
      @cocktails = policy_scope(Cocktail).where("name ILIKE ?", "%#{params[:query]}%")
      authorize Cocktail
    else
      @cocktails = policy_scope(Cocktail)
      authorize Cocktail
    end
  end

  def show
    @dose = Dose.new
    @cocktail.doses = @cocktail.doses.includes(:ingredient)
  end

  def new
    @cocktail = Cocktail.new
    authorize @cocktail
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    authorize @cocktail
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  protected

  def resource_not_found
    message = "The cocktail you are looking for could not be found"
    flash[:alert] = message
    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
    authorize @dose
  end

  def create
    @dose = @cocktail.doses.new(dose_params)
    authorize @dose
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    authorize @dose
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit( :ingredient_id, :description)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    authorize @cocktail
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @cocktails = @user.cocktails.includes(:ingredients, :doses)
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <% if user_signed_in? %>
      <p>Hello <%= current_user.username %>!</p>
      <%= link_to "My cocktails", my_cocktails_path %>
    <% end %>
  <h1>All cocktails</h1>
  <%= link_to "Add new", new_cocktail_path %>


  <%= form_tag cocktails_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a cocktail"
    %>
  <% end %>

  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-10 col-sm-4 col-md-3">
        <div class="card-cocktail">
          <div class="card-photo">
            <% if cocktail.photo? %>
              <%= cl_image_tag cocktail.photo.path, width: 200, height: 150, crop: :fill %>
            <% else %>
              <%= image_tag 'default_cocktail.jpg', style:"height: 150px; width: 200px;" %>
            <% end %>
          </div>
          <div class="card-description">
            <h3><%= cocktail.name %></h3>
            <%= link_to "", cocktail_path(cocktail), id:"cocktail-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class = "container">

<h1>Add new cocktail</h1>
<%= simple_form_for (@cocktail) do |f| %>
  <%= f.input :name, label: "Cocktail name" %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to cocktails", root_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h2><%= @cocktail.name %></h2>
  <p><%= link_to "My cocktails", my_cocktails_path %></p>

  <% if policy(@cocktail).destroy?  %>
    <p><%= link_to "delete", cocktail_path(@cocktail), method: :delete %></p>
  <% end %>

  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-5">
      <div class="cocktail-show-photo">
        <% if @cocktail.photo? %>
          <%= cl_image_tag @cocktail.photo.path, width: 280, crop: :fill %>
        <% else %>
          <%= image_tag 'default_cocktail.jpg', style:"width: 280px;" %>
        <% end %>
      </div>
    </div>

    <div class="col-xs-offset-1 col-xs-10 col-sm-5">
      <div class="ingredients">
        <% if @cocktail.doses.any? %>
          <h3>Ingredients:</h3>
        <% end %>
        <% @cocktail.doses.each do |dose| %>
          <div class="dose">
            <% if dose.id %>
              <p><%= dose.description %> <%= dose.ingredient.name %></p>
              <% if policy(dose).destroy?  %>
                <p><%= link_to "delete", dose_path(dose), method: :delete %></p>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @cocktail.user == current_user %>
  <%= render 'doses/form'%>
<% end %>

app/views/doses/_form.html.erb
<div class="container">
  <h2>Add new dose to cocktail</h2>

  <%= simple_form_for [@cocktail,@dose] do |d| %>
    <%= d.association :ingredient %>
    <%= d.input :description, label:"Amount" %>
    <%= d.submit%>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-item">
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag('cocktail_drawing.jpg') %>
    </a>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <ul class="list-unstyled list-inline">
      <li><%= link_to "Back to cocktails", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Add new", new_cocktail_path %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "My cocktails", my_cocktails_path %></li>
          <li><a href="#">Dashboard</a></li>
          <li><%=link_to("Log out", destroy_user_session_path, method: :delete) %></li>
        </ul>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Back to cocktails", root_path %></li>
        <li><%= link_to "Add new", new_cocktail_path %></li>
      </ul>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <h3><%= @user.username %>'s cocktails</h3>
  <% if @cocktails.any? %>
    <div>
      <% @cocktails.each do |cocktail| %>
        <div style="padding: 10px 10px;"><%= link_to cocktail.name, cocktail_path(cocktail) %>
          <% if cocktail.ingredients.any? %>
            <ul>
              <% cocktail.ingredients.each do  |i| %>
                <li><%= i.name %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>